// src/program/sdk-types.ts
// The author-facing surface for program-led skills. This interface is the source
// of truth; HERA_SDK_DTS below is the .d.ts scaffolded into each program skill.

export interface Hera {
  /** Invocation args passed to run(hera, args). */
  args: unknown;
  /** Progress line -> ProgramResult.logs + heraLog on the parent. */
  log(message: string): void;
  /** Runs locally in the child (has shell + fs). No RPC. */
  sh(
    cmd: string,
    opts?: { cwd?: string; timeoutMs?: number }
  ): Promise<{ stdout: string; stderr: string; code: number }>;
  /** Path-guarded to the session directory; runs locally in the child. */
  file: {
    read(path: string): Promise<string>;
    write(path: string, content: string): Promise<void>;
    exists(path: string): Promise<boolean>;
    list(dir: string): Promise<string[]>;
  };
  /**
   * The model as a function. RPC'd to the parent: returns assistant text, or a
   * validated object when `schema` is supplied. Always an autonomous call in v1.
   */
  llm(
    prompt: string,
    opts?: { input?: unknown; schema?: object; executor?: string }
  ): Promise<unknown>;
}

/** Contents of the scaffolded hera-sdk.d.ts (authoring autocomplete). */
export const HERA_SDK_DTS = `// Auto-generated by Hera. The authoring surface for this program skill.
export interface Hera {
  args: unknown;
  log(message: string): void;
  sh(cmd: string, opts?: { cwd?: string; timeoutMs?: number })
    : Promise<{ stdout: string; stderr: string; code: number }>;
  file: {
    read(path: string): Promise<string>;
    write(path: string, content: string): Promise<void>;
    exists(path: string): Promise<boolean>;
    list(dir: string): Promise<string[]>;
  };
  llm(prompt: string, opts?: { input?: unknown; schema?: object; executor?: string }): Promise<unknown>;
}
`;

/** Contents of the scaffolded run.ts entry template. */
export const RUN_TS_TEMPLATE = `import type { Hera } from "./hera-sdk";

export default async function run(hera: Hera, args: unknown) {
  hera.log("program started");
  // Deterministic step:
  const status = await hera.sh("git status --short");
  // Model as a function (uncomment to use):
  // const summary = await hera.llm("Summarize these changes", {
  //   input: status.stdout,
  //   schema: { type: "object", properties: { title: { type: "string" } }, required: ["title"] },
  // });
  return { ok: true, changed: status.stdout.trim().length > 0 };
}
`;

/** Contents of the scaffolded SKILL.json for a program skill. */
export const SKILL_JSON_TEMPLATE = (name: string, description: string): string =>
  JSON.stringify({ name, description, trigger: "", category: "user", program: "run.ts" }, null, 2) +
  "\n";
