import { readFile, writeFile, mkdir, readdir, stat, rm } from "node:fs/promises";
import { join, relative, sep } from "node:path";
import type { SkillDefinition, SkillPackage, SkillFile, SkillTrigger } from "../types.js";
import type { MemoryStore } from "../memory/store.js";
import { CAVEMAN_SKILL } from "./caveman.js";
import { INIT_SKILL } from "./init.js";
import { SKILL_COMBO_SKILL } from "./skill-combo.js";
import { MEMORY_SKILL } from "./memory.js";
import { EVOLUTION_SKILL } from "./evolution.js";
import { SUBAGENT_SKILL } from "./subagent.js";
import { COMMUNICATE_SKILL } from "./communicate.js";
import { AUTO_COMPACT_SKILL } from "./auto-compact.js";
import { WORKFLOW_ORCHESTRATION } from "./workflow-orchestration.js";
import { BRAINSTORMING } from "./brainstorming.js";
import { SKILL_CREATOR } from "./skill-creator.js";

const BUILTIN_SKILLS: SkillDefinition[] = [
  CAVEMAN_SKILL,
  INIT_SKILL,
  SKILL_COMBO_SKILL,
  MEMORY_SKILL,
  EVOLUTION_SKILL,
  SUBAGENT_SKILL,
  COMMUNICATE_SKILL,
  AUTO_COMPACT_SKILL,
  WORKFLOW_ORCHESTRATION,
  BRAINSTORMING,
  SKILL_CREATOR,
];

/** Files auto-generated by writePackageToDisk and excluded from files[] */
const AUTO_GENERATED_FILES = ["SKILL.json", "SKILL.md", "config.json"];

/**
 * Normalize a file path to forward slashes (cross-platform).
 */
function normalizePath(p: string): string {
  return p.split(sep).join("/");
}

/**
 * Recursively collect all file paths under a directory.
 */
async function collectFilePaths(dir: string, base: string): Promise<string[]> {
  const entries = await readdir(dir, { withFileTypes: true });
  const paths: string[] = [];
  for (const entry of entries) {
    const fullPath = join(dir, entry.name);
    if (entry.isDirectory()) {
      const sub = await collectFilePaths(fullPath, base);
      paths.push(...sub);
    } else {
      paths.push(relative(base, fullPath));
    }
  }
  return paths;
}

/**
 * Convert any SkillDefinition | SkillPackage input to a SkillPackage.
 * Plain SkillDefinition inputs are auto-converted.
 */
function toPackage(skill: SkillDefinition | SkillPackage): SkillPackage {
  if ("files" in skill || "config" in skill) return skill as SkillPackage;
  const def = skill as SkillDefinition;
  return {
    name: def.name,
    description: def.description,
    trigger: def.trigger,
    prompt: def.prompt,
    category: def.category,
    intensity: def.intensity,
    config: {},
    files: [],
    dependencies: [],
    chains: [],
    scripts: [],
    metadata: {},
  };
}

function triggerToString(trigger: string | SkillTrigger): string {
  if (typeof trigger === "string") return trigger;
  return [...trigger.patterns, ...trigger.keywords, ...(trigger.toolCalls ?? [])].join(", ");
}

/**
 * Convert a SkillPackage to a SkillDefinition for backward compatibility.
 */
function packageToDefinition(pkg: SkillPackage): SkillDefinition {
  return {
    name: pkg.name,
    description: pkg.description,
    trigger: triggerToString(pkg.trigger),
    prompt: pkg.prompt,
    category: pkg.category ?? "user",
    intensity: pkg.intensity,
  };
}

export class SkillManager {
  private store: MemoryStore;
  private skillsDir: string;
  private loadedSkills: Map<string, SkillDefinition> = new Map();
  private loadedPackages: Map<string, SkillPackage> = new Map();

  constructor(store: MemoryStore, skillsDir: string) {
    this.store = store;
    this.skillsDir = skillsDir;
  }

  async init(): Promise<void> {
    await mkdir(this.skillsDir, { recursive: true });

    for (const skill of BUILTIN_SKILLS) {
      this.loadedSkills.set(skill.name, skill);
    }

    // Load legacy SkillDefinition entries from MemoryStore
    const stored = await this.store.list("skill");
    for (const mem of stored) {
      try {
        const skill = JSON.parse(mem.content) as SkillDefinition;
        if (!this.loadedSkills.has(skill.name)) {
          this.loadedSkills.set(skill.name, skill);
        }
      } catch {
        // skip
      }
    }

    // Load SkillPackage entries from disk directories
    const entries = await readdir(this.skillsDir, { withFileTypes: true });
    for (const entry of entries) {
      if (!entry.isDirectory()) continue;
      const skillDir = join(this.skillsDir, entry.name);
      try {
        const pkg = await this.readPackageFromDisk(entry.name, skillDir);
        if (pkg) {
          this.loadedPackages.set(entry.name, pkg);
          this.loadedSkills.set(entry.name, packageToDefinition(pkg));
        }
      } catch {
        // skip corrupted entries
      }
    }
  }

  // --- SkillPackage-based methods ---

  /**
   * Create a skill. Accepts both SkillDefinition (auto-converts to SkillPackage)
   * and SkillPackage. All skills are stored using the directory format.
   */
  async createSkill(skill: SkillDefinition | SkillPackage): Promise<void> {
    const pkg = toPackage(skill);
    const def = packageToDefinition(pkg);

    this.loadedSkills.set(def.name, def);
    this.loadedPackages.set(pkg.name, pkg);

    // Persist legacy entry in MemoryStore for fallback
    await this.store.save({
      id: `skill-${def.name}`,
      type: "skill",
      content: JSON.stringify(def),
      timestamp: Date.now(),
      metadata: { name: def.name, trigger: def.trigger },
    });

    await this.writePackageToDisk(pkg);
  }

  /**
   * Load a SkillPackage from disk by name.
   */
  async loadSkill(name: string): Promise<SkillPackage | undefined> {
    const skillDir = join(this.skillsDir, name);
    try {
      await stat(skillDir);
    } catch {
      return undefined;
    }
    return this.readPackageFromDisk(name, skillDir);
  }

  /**
   * Delete a skill entirely (directory + memory store).
   */
  async deleteSkill(name: string): Promise<boolean> {
    if (this.isBuiltin(name)) return false;

    this.loadedSkills.delete(name);
    this.loadedPackages.delete(name);

    await this.store.delete("skill", `skill-${name}`).catch(() => {});

    const skillDir = join(this.skillsDir, name);
    try {
      await rm(skillDir, { recursive: true, force: true });
    } catch {
      // ok
    }
    return true;
  }

  /**
   * Get a SkillPackage by name.
   */
  getSkillPackage(name: string): SkillPackage | undefined {
    return this.loadedPackages.get(name);
  }

  /**
   * List all loaded SkillPackages.
   */
  listSkillPackages(): SkillPackage[] {
    return Array.from(this.loadedPackages.values());
  }

  // --- Backward-compatible SkillDefinition methods ---

  isBuiltin(name: string): boolean {
    return BUILTIN_SKILLS.some((s) => s.name === name);
  }

  getSkill(name: string): SkillDefinition | undefined {
    return this.loadedSkills.get(name);
  }

  getAllSkills(): SkillDefinition[] {
    return Array.from(this.loadedSkills.values());
  }

  getSkillMap(): Map<string, SkillDefinition> {
    return new Map(this.loadedSkills);
  }

  upgradeSkillsToAgentPrompt(
    agentName: string,
    skillNames: string[],
    agentDescription: string
  ): string {
    const skillPrompts = skillNames
      .map((name) => {
        const skill = this.loadedSkills.get(name);
        if (!skill) return null;
        return `## Skill: ${skill.name}\n${skill.prompt}`;
      })
      .filter(Boolean)
      .join("\n\n");

    return [
      `# Agent: ${agentName}`,
      ``,
      agentDescription,
      ``,
      "You are an autonomous agent created by Hera. You embody the following skills:",
      ``,
      skillPrompts,
      ``,
      "## Directives",
      "- Apply all embedded skills in every response",
      "- Maintain skill intensity and style consistently",
      "- Report outcomes concisely",
      "- Use memory to persist important findings",
      "- Reflect on performance and evolve when appropriate",
      "- Collaborate with team members when asked",
    ].join("\n");
  }

  // --- Private helpers ---

  private async writePackageToDisk(pkg: SkillPackage): Promise<void> {
    const skillDir = join(this.skillsDir, pkg.name);
    await mkdir(skillDir, { recursive: true });

    // SKILL.json (metadata)
    const metadata = {
      name: pkg.name,
      description: pkg.description,
      trigger: pkg.trigger,
      category: pkg.category,
      intensity: pkg.intensity,
      createdAt: pkg.createdAt ?? Date.now(),
    };
    await writeFile(join(skillDir, "SKILL.json"), JSON.stringify(metadata, null, 2), "utf-8");

    // SKILL.md (core prompt)
    await writeFile(join(skillDir, "SKILL.md"), pkg.prompt, "utf-8");

    // config.json (optional)
    if (pkg.config && Object.keys(pkg.config).length > 0) {
      await writeFile(join(skillDir, "config.json"), JSON.stringify(pkg.config, null, 2), "utf-8");
    }

    // Additional files (scripts, templates, references)
    if (pkg.files && pkg.files.length > 0) {
      for (const file of pkg.files) {
        const filePath = join(skillDir, file.path);
        const fileDir = join(filePath, "..");
        await mkdir(fileDir, { recursive: true });
        await writeFile(filePath, file.content, "utf-8");
      }
    }
  }

  private async readPackageFromDisk(
    name: string,
    skillDir: string
  ): Promise<SkillPackage | undefined> {
    const metadataJson = await readFile(join(skillDir, "SKILL.json"), "utf-8").catch(() => null);
    if (!metadataJson) return undefined;

    let metadata: Record<string, unknown>;
    try {
      metadata = JSON.parse(metadataJson);
    } catch {
      return undefined;
    }

    const prompt = await readFile(join(skillDir, "SKILL.md"), "utf-8").catch(() => "");

    const configJson = await readFile(join(skillDir, "config.json"), "utf-8").catch(() => null);
    let config: Record<string, unknown> | undefined;
    if (configJson) {
      try {
        config = JSON.parse(configJson);
      } catch {
        /* ignore */
      }
    }

    const allPaths = await collectFilePaths(skillDir, skillDir).catch(() => []);
    const extraFiles: SkillFile[] = [];
    for (const p of allPaths) {
      const normalized = normalizePath(p);
      if (AUTO_GENERATED_FILES.some((f) => normalized === f || normalized.startsWith(f + "/")))
        continue;
      const content = await readFile(join(skillDir, p), "utf-8").catch(() => "");
      if (content !== undefined) {
        extraFiles.push({ path: normalized, content });
      }
    }

    return {
      name: (metadata.name as string) ?? name,
      description: (metadata.description as string) ?? "",
      trigger: (metadata.trigger as string | SkillTrigger) ?? "",
      prompt,
      category: (metadata.category as "builtin" | "user") ?? "user",
      intensity: metadata.intensity as SkillPackage["intensity"],
      config: config ?? {},
      files: extraFiles,
      createdAt: metadata.createdAt as number | undefined,
      dependencies: [],
      chains: [],
      scripts: [],
      metadata: {},
    };
  }
}
