import type { WorkflowDefinition, AgentTemplateName } from "../types.js";

export const WORKFLOW_TEMPLATES: Record<string, WorkflowDefinition> = {
  "coder-workflow": {
    id: "coder-workflow",
    name: "Code Development Workflow",
    description: "Standard workflow for code changes: analyze → implement → test → review → approve",
    mode: "serial",
    steps: [
      {
        id: "step-1",
        name: "Analyze Requirements",
        type: "agent",
        executor: "self",
      },
      {
        id: "step-2",
        name: "Implement Changes",
        type: "agent",
        executor: "self",
        dependencies: ["step-1"],
      },
      {
        id: "step-3",
        name: "Run Tests",
        type: "tool",
        executor: "test_runner",
        dependencies: ["step-2"],
      },
      {
        id: "step-4",
        name: "Self Review",
        type: "agent",
        executor: "self",
        dependencies: ["step-3"],
      },
      {
        id: "step-5",
        name: "Request Approval",
        type: "approval",
        dependencies: ["step-4"],
      },
    ],
    createdAt: Date.now(),
    metadata: { template: true, agentType: "coder" },
  },

  "reviewer-workflow": {
    id: "reviewer-workflow",
    name: "Code Review Workflow",
    description: "Systematic code review: style + security + logic + tests in parallel",
    mode: "parallel",
    steps: [
      {
        id: "step-1",
        name: "Check Code Style",
        type: "agent",
        executor: "self",
      },
      {
        id: "step-2",
        name: "Security Scan",
        type: "tool",
        executor: "security_scanner",
      },
      {
        id: "step-3",
        name: "Logic Review",
        type: "agent",
        executor: "self",
      },
      {
        id: "step-4",
        name: "Test Coverage Check",
        type: "tool",
        executor: "coverage_checker",
      },
    ],
    createdAt: Date.now(),
    metadata: { template: true, agentType: "reviewer" },
  },

  "tester-workflow": {
    id: "tester-workflow",
    name: "Testing Workflow",
    description: "Comprehensive testing: unit → integration → e2e → report",
    mode: "serial",
    steps: [
      {
        id: "step-1",
        name: "Run Unit Tests",
        type: "tool",
        executor: "test_runner",
      },
      {
        id: "step-2",
        name: "Run Integration Tests",
        type: "tool",
        executor: "test_runner",
        dependencies: ["step-1"],
      },
      {
        id: "step-3",
        name: "Run E2E Tests",
        type: "tool",
        executor: "test_runner",
        dependencies: ["step-2"],
      },
      {
        id: "step-4",
        name: "Generate Test Report",
        type: "agent",
        executor: "self",
        dependencies: ["step-3"],
      },
    ],
    createdAt: Date.now(),
    metadata: { template: true, agentType: "tester" },
  },

  "documenter-workflow": {
    id: "documenter-workflow",
    name: "Documentation Workflow",
    description: "Documentation process: analyze → write → review → publish",
    mode: "serial",
    steps: [
      {
        id: "step-1",
        name: "Analyze Code",
        type: "agent",
        executor: "self",
      },
      {
        id: "step-2",
        name: "Write Documentation",
        type: "agent",
        executor: "self",
        dependencies: ["step-1"],
      },
      {
        id: "step-3",
        name: "Review Documentation",
        type: "agent",
        executor: "reviewer",
        dependencies: ["step-2"],
      },
      {
        id: "step-4",
        name: "Approval Gate",
        type: "approval",
        dependencies: ["step-3"],
      },
    ],
    createdAt: Date.now(),
    metadata: { template: true, agentType: "documenter" },
  },

  "team-workflow": {
    id: "team-workflow",
    name: "Team Collaboration Workflow",
    description: "Multi-agent coordination: plan → parallel dev/test/docs → review → approve",
    mode: "dag",
    steps: [
      {
        id: "step-1",
        name: "Planning",
        type: "agent",
        executor: "coordinator",
      },
      {
        id: "step-2",
        name: "Development",
        type: "agent",
        executor: "coder",
        dependencies: ["step-1"],
      },
      {
        id: "step-3",
        name: "Testing",
        type: "agent",
        executor: "tester",
        dependencies: ["step-2"],
      },
      {
        id: "step-4",
        name: "Documentation",
        type: "agent",
        executor: "documenter",
        dependencies: ["step-2"],
      },
      {
        id: "step-5",
        name: "Review",
        type: "agent",
        executor: "reviewer",
        dependencies: ["step-3", "step-4"],
      },
      {
        id: "step-6",
        name: "Approval Gate",
        type: "approval",
        dependencies: ["step-5"],
      },
    ],
    createdAt: Date.now(),
    metadata: { template: true, agentType: "team" },
  },

  "architect-workflow": {
    id: "architect-workflow",
    name: "Architecture Design Workflow",
    description: "Architecture design: research → design → review → document",
    mode: "serial",
    steps: [
      {
        id: "step-1",
        name: "Research Requirements",
        type: "agent",
        executor: "self",
      },
      {
        id: "step-2",
        name: "Design Architecture",
        type: "agent",
        executor: "self",
        dependencies: ["step-1"],
      },
      {
        id: "step-3",
        name: "Peer Review",
        type: "agent",
        executor: "reviewer",
        dependencies: ["step-2"],
      },
      {
        id: "step-4",
        name: "Document Design",
        type: "agent",
        executor: "documenter",
        dependencies: ["step-3"],
      },
      {
        id: "step-5",
        name: "Approval Gate",
        type: "approval",
        dependencies: ["step-4"],
      },
    ],
    createdAt: Date.now(),
    metadata: { template: true, agentType: "architect" },
  },

  "debugger-workflow": {
    id: "debugger-workflow",
    name: "Debugging Workflow",
    description: "Systematic debugging: reproduce → analyze → fix → verify",
    mode: "serial",
    steps: [
      {
        id: "step-1",
        name: "Reproduce Issue",
        type: "agent",
        executor: "self",
      },
      {
        id: "step-2",
        name: "Analyze Root Cause",
        type: "agent",
        executor: "self",
        dependencies: ["step-1"],
      },
      {
        id: "step-3",
        name: "Implement Fix",
        type: "agent",
        executor: "coder",
        dependencies: ["step-2"],
      },
      {
        id: "step-4",
        name: "Verify Fix",
        type: "agent",
        executor: "tester",
        dependencies: ["step-3"],
      },
    ],
    createdAt: Date.now(),
    metadata: { template: true, agentType: "debugger" },
  },

  "optimizer-workflow": {
    id: "optimizer-workflow",
    name: "Optimization Workflow",
    description: "Performance optimization: profile → optimize → benchmark → validate",
    mode: "serial",
    steps: [
      {
        id: "step-1",
        name: "Profile Performance",
        type: "tool",
        executor: "profiler",
      },
      {
        id: "step-2",
        name: "Identify Bottlenecks",
        type: "agent",
        executor: "self",
        dependencies: ["step-1"],
      },
      {
        id: "step-3",
        name: "Implement Optimizations",
        type: "agent",
        executor: "coder",
        dependencies: ["step-2"],
      },
      {
        id: "step-4",
        name: "Run Benchmarks",
        type: "tool",
        executor: "benchmark_runner",
        dependencies: ["step-3"],
      },
      {
        id: "step-5",
        name: "Validate Results",
        type: "agent",
        executor: "self",
        dependencies: ["step-4"],
      },
    ],
    createdAt: Date.now(),
    metadata: { template: true, agentType: "optimizer" },
  },

  "researcher-workflow": {
    id: "researcher-workflow",
    name: "Research Workflow",
    description: "Research process: gather → analyze → synthesize → document",
    mode: "serial",
    steps: [
      {
        id: "step-1",
        name: "Gather Information",
        type: "agent",
        executor: "self",
      },
      {
        id: "step-2",
        name: "Analyze Findings",
        type: "agent",
        executor: "self",
        dependencies: ["step-1"],
      },
      {
        id: "step-3",
        name: "Synthesize Insights",
        type: "agent",
        executor: "self",
        dependencies: ["step-2"],
      },
      {
        id: "step-4",
        name: "Document Research",
        type: "agent",
        executor: "documenter",
        dependencies: ["step-3"],
      },
    ],
    createdAt: Date.now(),
    metadata: { template: true, agentType: "researcher" },
  },

  "general-workflow": {
    id: "general-workflow",
    name: "General Task Workflow",
    description: "Generic workflow: analyze → execute → verify → report",
    mode: "serial",
    steps: [
      {
        id: "step-1",
        name: "Analyze Task",
        type: "agent",
        executor: "self",
      },
      {
        id: "step-2",
        name: "Execute Task",
        type: "agent",
        executor: "self",
        dependencies: ["step-1"],
      },
      {
        id: "step-3",
        name: "Verify Results",
        type: "agent",
        executor: "self",
        dependencies: ["step-2"],
      },
      {
        id: "step-4",
        name: "Report Completion",
        type: "agent",
        executor: "self",
        dependencies: ["step-3"],
      },
    ],
    createdAt: Date.now(),
    metadata: { template: true, agentType: "general" },
  },
};

export const AGENT_TEMPLATE_TO_WORKFLOW: Record<AgentTemplateName, string> = {
  general: "general-workflow",
  coder: "coder-workflow",
  reviewer: "reviewer-workflow",
  researcher: "researcher-workflow",
  coordinator: "team-workflow",
  architect: "architect-workflow",
  debugger: "debugger-workflow",
  tester: "tester-workflow",
  documenter: "documenter-workflow",
  optimizer: "optimizer-workflow",
};
